# Generated by Django 2.1.5 on 2020-10-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_eventmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='altitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.IntegerField(),
        ),
    ]
