# Generated by Django 2.1.5 on 2020-10-17 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201017_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmember',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='eventmember',
            old_name='user_id',
            new_name='user',
        ),
    ]
