# Generated by Django 2.1.5 on 2020-10-17 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20201018_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='myapp.Event'),
        ),
    ]
